name: CI

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/ci.yml"
      - "tauri-app/src/**"
      - "tauri-app/src-tauri/**"
      - "tauri-app/package.json"
  pull_request:
    branches:
      - main
    paths:
      - "tauri-app/src/**"
      - "tauri-app/src-tauri/**"
      - "tauri-app/package.json"

env:
  VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
  VITE_REDIRECT_URL: ${{ secrets.VITE_REDIRECT_URL }}
  VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
  VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
  TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
  TAURI_BUNDLE: all

jobs:
  build-linux:
    runs-on: ubuntu-latest
    name: Build Linux x86_64

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: src-tauri

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install
        working-directory: tauri-app

      - name: Check Tauri version
        run: bun tauri --version
        working-directory: tauri-app

      - name: Build Tauri App
        run: bun tauri build --target x86_64-unknown-linux-gnu --bundles deb
        working-directory: tauri-app

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-app-linux-x64-ci
          path: |
            tauri-app/src-tauri/target/x86_64-unknown-linux-gnu/release/**/*.deb